// export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_HEADER_SUCCESS = "GET_HEADER_SUCCESS";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_DUMMEY_TEMPLATE_SUCCESS = 'GET_DUMMEY_TEMPLATE_SUCCESS';
// export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_FOOTER_SUCCESS = "GET_FOOTER_SUCCESS";
// export const GET_SINGLE_PRODUCT_DETAILS = "GET_SINGLE_PRODUCT_DETAILS";

// export const SET_SINGLE_PRODUCT_DETAILS = "SET_SINGLE_PRODUCT_DETAILS";

export const GET_HERO_SUCCESS = "GET_HERO_SUCCESS";
export const GET_PARA_SUCCESS = "GET_PARA_SUCCESS";
export const GET_HEAD_SUCCESS = "GET_HEAD_SUCCESS";
export const GET_DIVIDER_SUCCESS = "GET_DIVIDER_SUCCESS";
export const GET_SIGNATURE_SUCCESS = "GET_SIGNATURE_SUCCESS";
export const GET_SURVEY_SUCCESS = "GET_SURVEY_SUCCESS";
export const GET_CTA_SUCCESS = "GET_CTA_SUCCESS";
export const GET_REFERENCE_SUCCESS = "GET_REFERENCE_SUCCESS";
export const GET_SPEAKERMODULE_SUCCESS = "GET_SPEAKERMODULE_SUCCESS";
export const GET_SUBJECTLINE_SUCCESS="GET_SUBJECTLINE_SUCCESS";
export const GET_PREHEADER_SUCCESS="GET_PREHEADER_SUCCESS";
export const GET_PCI_SUCCESS="GET_PCI_SUCCESS";
export const GET_IPC_SUCCESS="GET_IPC_SUCCESS";
export const GET_BODY_SUCCESS = "GET_BODY_SUCCESS";
export const GET_IP_SUCCESS = "GET_IP_SUCCESS";
export const GET_PMNUMBER_SUCCESS = "GET_PMNUMBER_SUCCESS";
export const GET_BRANDTHEME_SUCCESS = "GET_BRANDTHEME_SUCCESS";
export const GET_CIMG_SUCCESS = "GET_CIMG_SUCCESS";
export const GET_UPDATECIMGMODAL_SUCCESS = "GET_UPDATECIMGMODAL_SUCCESS";
export const GET_I2CTA_SUCCESS = "GET_I2CTA_SUCCESS";
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
export const GET_SERVERIMAGES_SUCCESS = "GET_SERVERIMAGES_SUCCESS";
export const GET_HEADERIMAGES_SUCCESS = "GET_HEADERIMAGES_SUCCESS";
export const GET_FOOTERIMAGES_SUCCESS = "GET_FOOTERIMAGES_SUCCESS";
export const GET_SPACING_SUCCESS = "GET_SPACING_SUCCESS";
export const GET_USERCODE_SUCCESS = "GET_USERCODE_SUCCESS";
export const GET_CURSOR_POINTER_SUCCESS = "GET_CURSOR_POINTER_SUCCESS";
export const GET_CAPSUL_TIMER_SUCCESS = 'GET_CAPSUL_TIMER_SUCCESS';
export const GET_CUSTOM_CSS_SUCCESS = 'GET_CUSTOM_CSS_SUCCESS';
export const UPDATE_AST_DOCUMENT = 'UPDATE_AST_DOCUMENT';
export const UNDO_AST = 'UNDO_AST';
export const REDO_AST = 'REDO_AST';

